# Generated by Django 4.2.5 on 2023-09-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_book_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='username',
        ),
    ]
