# Generated by Django 4.2.5 on 2023-10-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
    ]
